### ISSUE TITLE
Lavagenerator and comptibility with Liquid Pipes or Buckets from other Mods or Crystal Flux Support?

### ISSUE THREAD

**Issue by cyberpunkbln** [abused/Tech-Expansion#14]
Hello,

give it a choice to make Pressure Pipes Canister compatible for an right click?

All Lquid-Pipe-Systems (Buildcraft,PressurePipe,EnderTank) dont connect to the lavagenerator.

Or another chance to put automaticly lava in?

thx 1.11.2 is at the moment not so easy handible:) for complex liquid things:)

PS:ExtaUtils2 Compatibility was very very nice for transport liquids in the lava generator

**Comment by abused** [comment]
CrystalFlux isnt supported not because i dont want to but because it runs off of ForgeEnergy, Tech Expansion runs of RF so compatibility wont likely happen unless CrystalFlux starts to support RF, i'm going to be rewriting all of Tech Expansion so i will be fixing every bug possible and making it mod friendly, meaning yes the pipes will work with the lava gen
