### ISSUE TITLE
new forge 2203(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [abused/Tech-Expansion#5]
the new forge update made the quarry start building above itself and then even mining itself and all storage around it

was/is working fine on forge 1.11.2-2201
tech expansion:1.1

i know is this isnt intended for 1.11.2 but i was testing for compat

**Comment by abused** [comment]
Its not intended for 1.11.2 but will be updated to that soon, so dont worry, the current mod version is on an old 1.11 forge as the newer ones changed some code, so i have  to update it to fix that, otherwise there will just be problems, either way thanks for reporting this as it just reminds me to update to 1.11.2

**Comment by abused** [comment]
Update to 1.11.2 is done, it'll be out soon
