### ISSUE TITLE
Recipes don't support the Ore Dictionary

### ISSUE THREAD

**Issue by ManMan36** [abused/Tech-Expansion#8]
When I want to craft anything from this mod, it demands a certain type of copper, tin, silver, etc. What makes this even more annoying is that this doesn't always demand your ingots. In my world for example, the machines demand Abyssalcraft copper and tin.

forge version 2226
tech expansion version 1.4

**Comment by abused** [comment]
What exactly are you trying to craft? iv setup the crafting recipes so that they accept any of those resources thats oreDictionaried as such: ingotCopper ingotSilver ingotTin ingotLead, ETC. If you have a mod  that has any of those they are compatible with the recipe, if not it will default to those resources from the mod itself.
`        
GameRegistry.addRecipe(new ItemStack(ModBlocks.RFConduit), "XXX", "YZY", "XXX", 'X', getOreDictItemWithMeta("ingotInvar" ,1), 'Y', getOreDictItemWithMeta("ingotLead" ,1), 'Z', Items.REDSTONE);
`
thats an example of one of the recipes using the oreDictionaried variant of an item

**Comment by ManMan36** [comment]
For example, when attempting to craft the tin gear needed to make the metal bender, the crafting recipe only takes abyssalcraft tin. I tried another form and it wouldn't make the item.

**Comment by abused** [comment]
Hmm weird, ill look into it tonight

**Comment by abused** [comment]
Iv fixed all the oreDictionary issues and ill have an update out soon. :D
